### ISSUE TITLE
ugly readme

### ISSUE THREAD

**Issue by bezout** [charlybigoud/gsa#2]
Bonjour,

Il y a des $ dans le readme.

Cordialement,
Bezout

**Comment by charlybigoud** [comment]
Bonjour,

J'ai affreusement besoin de votre aide.
Pourriez vous m'aider à régler ce problème ? 

Très bien cordialement
Bigoud

**Comment by bezout** [comment]
Je préfère critiquer.

**Comment by charlybigoud** [comment]
Fixed ! Cela vous plait ?

**Comment by bezout** [comment]
ça voulait le coup d'attendre
